[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "75dcd7f89ff04c424057a459c2e96981d881eef6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "8a3ace5dd21cb934dce039c932c42d0802117801908a9673693c00f74c3767ed"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "80bde7e8f9f7c4d148bea94b1d94bd0a67141aff"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "0ae40ca17db54520d65546c373ce18a676b2cb80048e87a1cb119fa79201abd3"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "94ebdff1d0a7ce070c0c0388e9e06edc4d1b5a45"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "e3f6d478694548bc98c22a81e121ee795667332a17780aa86d7becb4251ed5d5"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "bae36b1e1ef12a6346bfb368dfb1541099482595"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "4202917e15e8b625a6a472b25f1d2fa7979b944870887bd2e8638253c4fa307d"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2b6f151c0dee61aae543573a61f55f77877b65ce"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "f1353a4fc0e14c797e8d593f2b08687bb91e711eaca242bd437a1993d83c6a40"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "83b4e463bcd394fee920377421b0de9b085f07ee"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "3e90f488b875a3b68dcdbac3651f7a7561849580bf17882ac59708c584841dd2"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "de59cdab596c135ead9c37f7b53f7f281336f165"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "3b664ba90fbd55b834db0b1364b128c541f9f88c9c6104eea939942e7a93049b"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a5b10ceb29a1a19c7a60432aa93ba9d618647dfc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "c7affeb5bd25f7064c3965551d70a09f5f3d07eaa888dbec9c88c5cc33c9bac4"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "c23f0e9f29ae067c675f3dfcc1ced31aca5adb55"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "deadeca791f24a110b4182d506967e85249544174614b1bba7e3e1f5ba142084"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.i686-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "75aef0a22009cc5a040c029e1a588fcfd20f2bcd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "bd2047009c74de586df29f9f4717a6fe5120ac2067fec66081d74016b7784d14"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.i686-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "16295bc1a3a5400bec5c94e65d10c74f11e7019d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "e6c6e08ef3ab4d50c32c8180ac96c0c418f809385b592994f03ee91247ce3eda"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.i686-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "bf529700af547766264bea73a549abc48e85984e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "cc18f0388f4815b1940c99c571cf62fdd70d2335606ba8411c0fa748c583e8b8"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.i686-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "83a92d6fe61a8a4df6fdad7bbc6d7a91d88a5b16"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "160178f571c4b9ded67ee70b744b14122d3dffa3eb965b9cc35d801865b957a6"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "a3f495c53548bd9ac8e79d063385633d2d44a588"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "3213a01d67357fbceb91c0b2733020ca22a057b60716bf254af91a4ab640c545"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "1f4fa9df9822146068e60357a9f19dadc8841ff1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "3f24217a0c009ae6163f0b2e26cb84fd4f27962ab508ef8f06542e4dd8309ad6"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "907689561b834d0404b6160ead0dbe0eb9662e74"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "8a5c5a5d6da704f36d7c45ddab8969128e11432cc0a5ecbb1a040e7864b829b7"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "eab545987e166b553f27a7e5afeacc1bd4ba2129"
libgfortran_version = "4.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "cbf19eddcb3ef4b9b8cc61f521f49c6efcd8a11e2adf21bb753f933239a9e4ca"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "dfdba3bcea6a1f9ea0298fce5458438d54f87b7a"
libgfortran_version = "5.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "27719de0da7cbd8e8d5aca73b9c5cb82f93ac34cd016609907b64dbf0a27a4d9"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "8a0e243eb5667d05bde6d4ceb4b5fef57a855d80"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "f82721aa569303112b9d85c1101938ee16c3f4171bd53f5b146dca890f8dcf95"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "72455703f7063daf87757067418b11d402f6df7f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "8c4f307c8531acf4ba64483e06d1875180fdfac6fd6ad0f162bde800211fce63"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "2f0b8cfeb81bcb2e16ca2380670e1bd2d1fa9f87"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "4c478be7b44888f9abb758db6344471535f23a46b3add23da34c35d00415753e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "32679afb909da7e72951adc495a2df870fa3d231"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "491ed39605198c263f4ee35c4912d36d7b47289f1086c050bbb8b792896219fd"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "d2523fc87b613d05952bd13f01201e5326b64dca"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "a025a3e4ec82bcdb2288dd2cd1a22ead84e537797859308dd956e4969679a4ca"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "0e75387580c500737046fbfde1edaa33866de68d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "7d7b7fbbd0056bd1a38a99f0f2c43c2ea44ecd06df0880dcd9edbe4b59c45c7e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "3f0071cb4374f31af9a52a03d9b382c2cf681b47"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "eb0b3b39a922be20004841899d169f943df55883d17cb948ddc8ef5989b16c34"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "eb669ecf432e42622bdbb779e6292c379229f329"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "e20eb2c387adab4ab98b70a2483bb76d5c333db81c6b6e13c0f44690677a546f"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+2/qr_mumps.v3.0.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
