[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "db35a037811a77c04946ff26227e9ba5b3b94530"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "26bcf87c8155b5f453a514ac3bd4a4a25dec462a4e352d6d6c6569426331b637"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.aarch64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "c4569a8aee10516bc8e50e7fa4da1bdd599dae7a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "b54ee3f6b2dbbc8d3c22c3554270d17c706e6f9536cc013db29793b1e48dca76"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.aarch64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "d805615ea23c762e4bcc9f98c01b43a3b59001c0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "9bdfe1a0ac953b03f4d0a826928bdc03df5f2d0c6892d530e9dd1c206b51464f"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.aarch64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "21f4eb3a2a28bb50f90141c2a157b499e0073b53"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "65e85a107553317028b2d11d1dd13a166779ef94576512c3709b40472264c538"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.aarch64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "110c4d23e0980a8ea95d7a4fc5cb53520f38948e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "bad075f01d65fdc660471cbfd56d263d462631e2179ab563be12808c9fb26b1c"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "de9248346650a248c2851c6b0eea11fdf7b05b07"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "087664749a4621347b806637e3d95abab697660f7e03d48862448017b0537be0"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d0c00bc070cd046820cf5610bd042856e598bffb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "23b49a21db8dceb87ba7961e9093c639a15aa8de343465b33d1b3a09e00c754e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef2137bb838a7caa71f29dbe197b6e7e7a7d5d0c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "2b813db5d93a22b05f5fb716fdcea9bd879a0f37844f9076ae1188b6efd22edf"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "7dce8ab6871ce55102628a8cdaec5665b674d23f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "d410750083abaf3eded2a07c151e8dcfcb0b280dc7509fb5f187bd5665d96ba0"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.i686-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "ed4bdba910965240ff456dfbd61d15816f043080"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "bc374f387cb2949c08290e70ba3b3f58f568f481856e1a7597476a7cc78a6921"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.i686-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "eb9ccd7e1e5a71ce7fe803a203c56f23352102d5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "1d046cd67e488e719f11e118a74d6952ed0c24668ef012d981034cdeb428276f"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.i686-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "54b3b6fb37322f0a09813880fdaac5b8b060e345"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "9b58e9007a258fb770360a324b4030360292df17fa187b42079865f328c12f35"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.i686-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "1ab118e1228778416af8176ded754e81bac4fe33"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "30cfe9156a157483a5440d1b0d83249f3735e9adec4cb042a308ef83533de5e9"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.i686-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "10e95f32cfc5c31e8580cb24b1212afcacdcb106"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "96541eb87822eba2d927c06749be6d8fe2dae4bcd4935b8c63cc87776d5c7134"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "4047b4b9fd7ee5ab97940596859cf6167aed7ecf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "730dca3fd9d9f7e675dd6b10e88c317b4d88196de83b5a708c0ae847c6b6814e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "a408fb2dc82df74621efe88455cc61d118272a9b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "aa60ffb71bea8b5e5ab1f1c48b071a51f36bf4861e4af7c6616141913ce66108"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "7b8df178cdc93c9c33977cca6617e28755759856"
libgfortran_version = "4.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "e47159b07ff43b3df2222f1e85fce9b5f919b5708a40ab75075d4b8f8cbb5bfa"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.x86_64-apple-darwin-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "777434820295885defacb36d5ca3779f2c1b7b27"
libgfortran_version = "5.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "4467a54c95f10a5c190d61601837efb54e586d6a7eedb8673f8c4cad36edb594"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.x86_64-apple-darwin-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "e623666795ef17eb5e9ab7f824587f6ceeccdae6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "ac5516161643f80593a323015b715012db86579a0b38bb44323f1ccf48483169"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "a683c1f3847a707ab904f377d4ddde8d2a89f8a3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "6e80c7d2c61c0f0d11a21bd677e7ad5d19687060088e5810298692fecbc671e5"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "2fa8a17602850d6ffc465537b5d9d00a10d86287"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "9f9b17eb77381f9e0169ca0812dc26c3e923704382aae90569d5b9f4f879662e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.x86_64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "cee31ede5098717ec1fa74b3475c047ae4b89e03"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "37bfff2cf6ee579b466a4ceb448d40318686f933f9f8c41b31582832f7b59438"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.x86_64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "db100f63b421cb439e5621e960070e155cf287a8"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "d70c9095a35a3e987ae71a50d7f768a7a1dd3a91a8a96128626d6423c983bbc9"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "ad4f207cbf719afee96e9abc10b8b9900ea09b2a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "f8d9d722d05de364ab378719b39230c98889e75b48832967ff9031e64cd215e9"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "60f43707506bb7185368d6ea0a892831f8b9906d"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "27aa270601e304cff55a8d79d47d574c5b44f59a497237ce76547f02f6d1493d"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "aca44591552426484ad90fb929c3ace7f6bb606a"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "cac931bc9856bc6012a3922eeae902dc5d7da0452f338ee015a5e1ae15a11acf"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.3+0/qr_mumps.v3.0.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
