[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "38c4000bdfe99d61c1efbf9d0c881c4786d2b70a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "700ca573f0729e86a85e6edb93a33f8dee332117a6aede91957e466a5d11c766"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "51cf28ee38478003451d30a9c5a4e622df077fbe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "b8e9d7aae8f23429bc704f66c42ee5adbe160bfaa0a6f9973498e91a8655dea9"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "d42249a701d100f812b576f81b5b0e5a9cd29ccd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "dc9c4eb2a17fad9d8afe7c1900fbf8b033c48216855248262a1bccb70aecabd5"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "5e9c9dff95cd96aa5a57d08decbb95c8fe6c09b9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "950f22065c3128d36dee186426f88f6bd94f049a75f565ceebdebd8272fcd851"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c25035c31eabfba048168580559ab6818434abf6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "3827de88297f15be0722e6086b8e8d05f015311243ed94cf5c6fc8d9084b9dbe"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7a4b1639c25ad7eaf94e93a4a664143bb76f7747"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "deaecbe50196a41e1b6acafd98d9f93190920b7b171a40a55f70247da401de22"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c0fb26bf5c5aa1492fa54ca44317516b3c65c830"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "4201c8c1fed4b320cf9e560de00e6e59fc3ca64889e7a4f83b55547c22d8dd90"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b3003b899b9642374df72b506d2534f2deae64a1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "788bad1b6cd71b1a71d45dbbac58ef4ac2d7201a4b15f3115941f27c52f63b18"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "97b9672245301fee682ac75c7cd30fcf45531933"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "e011e8e609678794d016344ccaeec55ab5c66b4478ae3498b8dd2f8de3833fc2"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.i686-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "073b01c4d936b4bc0e6b11782e8c44ef7ba97379"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "a3ca9d4f335695be41a0e219ddbae72e7589948f67c1d21c09e486b73b73f371"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.i686-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "801301e1868ac0fedea4237df71f917c94868781"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "cfb07335ca30d866116725e511277196ccc7823ab2aa2d953a84bf0e376074ae"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.i686-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "562111b851bf762ab80f7baa8a4e4daa63fdf21a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "78430da51335bb4cd8113395b856c9c44c2a4cc9c21845f817cb6c57c3b7d7b6"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.i686-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "440b0d155e992a0a93121d958bcdfef49c49d40c"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "e5b28af5053cc753bb0cebbc2f9ad5cb5b530f1f8c1439e5affae30e3030b131"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "a4b649cd8dd7ad7e810d7bc2fd2eae5d3ae1fce1"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "45703db3b0fc276b0ca8c3954a5645ec698a3616c79ac6a8e2447b38620da088"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "48fe8d2d79e36ca2edc31c2884aee9c0c865269d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "568bc76b3b3bbe4eb9d9768debea375fc411ec1747530f5e9d8446f4c7f8dd49"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "a8f01893267866ef292d43c7c802f9d6abebf0bc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "3618f9341c72a2648b19aa2e17b56e8c48f212dc70e9b83eaf04dbedd383ca30"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "dc12699fd157b81a2a82a83bc44d7613dc64afb9"
libgfortran_version = "4.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "6404c290417007b793e10eae37346662f78099158367c5775a873c76cf226f0e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "b104732078f4529550e958667916de694e6f1482"
libgfortran_version = "5.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "7772b9c836503d1ad75130b2bc636d150fedbd1aa8a82b3313c533b5dc6dd015"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "70ccb2ab37967f1e4b71416ef79db7595ed355cf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "039a5ffe6a88c04426557180865a70341fbe2396b07464ecd4105b02ada9e5f4"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "a2a57127a1bf9df226ca1d29c1c228b646a72b75"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "227ddbaa313579c022a5135998121df66ac029018590615513f264de12ed8e28"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "3359d0bfdca5dec527d0a0c6020f1c164e192208"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "2f6b3e34a447db50eb3347aad22b31d94515300df7887b5ba7e9e6c0d5c029b5"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "72a08792fa46d0f39a59c571948395f5758f258b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "386cb9405cdbfa74d2772b5a861a2827eeb13e4abf152e103e34789a9341a162"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "95091efae6aa137d1fd7eaed28360fe0aee9df1f"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "0ba1e7b834e65f3291ebb32939100d987d61ded2c3415ad9a5c4c7afef0ce030"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "0723bf8f48a48253861ec7b18ef9b84943b3e5b1"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "40dfdaabf301b1cc5312404e873f4b6b3e5069c892401a840d922c65904efa7c"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "208f9339208d846b34728d93b292f669e6c5798c"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "e36da82f64e3a3db6acb16b8082770690c62f7dbb6ead524c7441b990609cd6b"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "b1752da62ae4244616e7c61ecf3b348fc413ef2e"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "552e17d627606dd26cd2f51579833af0177862b38ee232fa868026e9f63d08c3"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+5/qr_mumps.v3.0.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
