[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "40fe82d6a2a620077f830ac51f78ecb8b0c52678"
libgfortran_version = "5.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "0c0f95b4c1e4054f7cbebe0b20c3479ada7b0396b8daaf53b5959227474df22c"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "7ff9ae13fd42d7e0d3b502e67476f065555ca14d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "23ce8cd1b7923ba722b60d798526691efb31a2aadb252ce2cc814ecd34fb0ebc"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "cd359ff622743fe9b1dfa956efc68e8979af616a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "73c6b95b266ff0f12063b16630bf28531b9b067eeea63cdd632972739587b743"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "be628ed645c7f20364390ca7c363ada0e4770cc3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "b1f08b523f69cb0f6f14f7a81894e5d028835e5bbfb1c44ee4abcae0777a8b5b"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "2f96a0bf3d19b279b1006e008580425b6bf11b9f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "6d3429a5133183ddddb3af0336ed13ee9dd089443387a5bd17064dd6ccf2a9bf"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "15a06cea21e02341f5a5c54bc040c4a391521ae9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "b0a39cbaab8a2d567e3942023841dd547fdec30ca7112ee5ddbeed45f397d62c"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7a97df8e97876d0db3d46200b6118d13886bcefd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "71730546ef7e5b2a1b8e8e6b0731a902c083f3ce97916f2948fe65367f0f64be"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1dd5b52ad19edbacb1377a2243d31689050a4dab"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "c4ba4bdaca1f2ffc392eb04b309df957d1d0b5a3b8d9d4627a42ce27048ccb83"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6a0a880b15fbc7a3889657062f7e63811b6236c3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "6347af5be4bcbe9d4156dae0007a2ec249aa211fdd8bbe417f2cbe44451adb69"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "28be9e5f98fc303168be96c145e72fa944f8f3b6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "b16b9a264bb255ba06f932976f7d718bc2b3ffc652c5840969dc8ad68af4b39d"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9cfff76e37a7e7cd0506a037459316374107b77f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "d9132844b2e974f884341c4db6a597e1ecfce0fbf910580a9ba9f57f3c597a41"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6479b5fa111e868881b77b4881b110cc01926645"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "b8568fb0da75f5d7e25c916a1affe459edf264798602505309bf6a3029cd6061"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e9afbfef9e45fe0fa429ebbb99494017285fe7e2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "0d40719fadade3503f290d6cd29f6c78b9914d1cf6cd6072a2297c365e16b59b"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "0514686a6313e4afa8539301bf0073a246f1e4aa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "1b879a05b0fe925b5e7463abc04196d94bdc4373608e4fa46396270d5bfcaa65"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "978c70b8cec906cebd8b613d8df714878dfe144a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "c4fe7b4be65dabf28cf216dcfca650490b22f98c9db5817d849de6199e0dbf59"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "5b197ae5f50e715e27668fb5434246d050a06164"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "b51822d9882961fbf2ee703d853dbadb8d3173dc3099efa1d925b2684f56775a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.i686-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "2789714f642dcbee4cff70f3d8f23a3b675de38f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "78b91e354f2d552cf7e1be8befb3c5fb30e6c96e7ef22d6a817e2c652ed4ad6f"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "c0407c13409b9c9c94b7abb5ef8b14289e2b3383"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "68ed7c7a641fbcdb755dce57b635c260038f7aa0e9dc2133679430842a32fff9"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "7f2ba35aaf5853d2e01f2f8fed001cf5da2f6a7e"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "431699dede09fbab3c5fa6552af783a12d988832de12e7ec1d7849c08be15443"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "a96421f951f207585e1ff80712363d8ebc3c1bc3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "bf26517a04bc410f7dfc15606a61476c3ed97c4f54b84285843a00a01a84cd8e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "a7031175e97bea462ff3ec00795a9bf329f9c213"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "46c7d40782029556951d5c46c20f4d52981dde0ea12d103992a4ffcf6b3e631c"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "5c6391349bf210289743537a4efdf66472933666"
libgfortran_version = "4.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "1db598e60e5f7b0ec58a1f4a4fc69e128b491cacb3f327016a882d87ec79190a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "0b683c4dc77cdf8b1b709b925066db1bc0fc0e2e"
libgfortran_version = "5.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "5005a6d83f69901d28bc64ca7ee5b8c2069106291905c57c5d33f09f82543fee"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "0a5e9a3b4aae2cc00bfb155f11a63f19d039b970"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "df52f9390a6e392a1d517b7472e661c5b30d4527b2f7798d4a645004ae45c001"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "93caeaf24f28505fec6e7a532e2b0aa1be73842f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "0a342a996096ba0e561db68f7b5d0b9011d1273785e5e1728be7db57d75558b2"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "cf0f20b29cf770929342658f68696a310e0e8a08"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "6d4796ee8f7d6c76d44ccd63a534c88c187afddc9a6abec2e659c6302fb3815f"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "d39a53943524c178aee98ffb26b954643351f314"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "6c681e6cf8a95dbf78185f6c3994d3ef88dd04c54d8ff4b97fec80905142a95a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "9a1db99c5632dda47802c0015b3b2c94e3228c89"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "264e68b25ba89507d4b9ef7cbf04e3c3b5d9539b2a26cf27b174c1292f00e6c7"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "10be05cda55787723523076426c07cda80448b99"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "ca9448edfd28f571bc9359b57fe74d53018d81e32cb3b1ba383597547d4cc116"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "90317733426b7213749cb2fc76d237aa0b2aa2be"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "c521742d871f58642f7165f8e73a42b17eb90f3c553bb851be841a8e7dceb096"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "38dfb1f478d6433261063adc0da8ef63342604ca"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "0389adfd496d43857cef8c7b9e4233a6a32e44c51d45162ba8b915513f880410"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.1.0+0/qr_mumps.v3.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
