[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "026c866ebe253f59b1d42d8fbc96a5dab7637e5c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "d4bab4fa3e39363c5167fd0821cbfcba805d99755c5d3518dc45cca9087ee3f7"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "ae79bd3273b8428edd9ec1463fcf0d4960c6e909"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "7ec33bd385b8a6d8fb61e7cdb05161c5120e32c27f140ad0aa5722193c13dcb2"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "121660291094869d322e166fda4fa2ddea593539"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "2ea98ff0a425f0b219429d215745c90e22cbd341a650f67faacde1215cb8f57b"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "6cad6c7b3d475c5a4d65f5b84dbc6bfde289e64b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "4b586a25f0d9740b7bfe6983343ba4526df3270abd4ea525e2103837d1497b67"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f1b812711146d2f4790ebd573c74d6166a9855bd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "6be53b773a68cb2c0a5061b60fed85c94674e1242a14de29b9501a25188cdd09"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bac2180974e64a4154cb6af60d32fa94ee060969"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "63a2b25394908acb991b59d1c219e2f51cc8f55812f1a703cbed7f48cbf52cfc"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2bb2d5ed7725b53a0d24c88c39815b956ae67107"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "9eba3d68b46c5be7fa48d2931dccdf0729622bb47a4b08f30433dc87a651033a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "46a705dd8334554338c7a447ac484748b4f33954"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "bb9e7b441b5e20466f5b4ac212a1403775329238c86e1efa107ce1d8ca58b19d"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "587131b9dc574070f58c50dba7f76ffb40c0f939"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "576c85a36ceece18a1a0982c50e0f879e4ed0d01bc4ef706ebb40f28729efa4e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.i686-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "121f10f1b8f04d92478e91dee8de2f6e6a801ce0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "71f9cfdacee8b969774965d6cb90fec41f444c57cb09d4d02d184cf543bebad8"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.i686-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "47ac2b75ac187f4b8b7cafe3a0fafb3c646d4126"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "3aa6890687aea04b930bee2cdc0476dc4ab0ea77f85bb9829ed165e6a1fdd87a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.i686-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "07f6433b5d6588bfdcd784f1106f6d899954b86e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "744e2106fca22e60a06949496bf898ed20c1405ddbc246792d72ab8b77824f2a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.i686-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "16228b22cd5b0bcb03266ea653be915668afc570"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "4c53da1cd9b5052647073bf420c41f18ccbfe2c86a8555840ccb5323e4505082"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "c500320559b492ae1e73113fd352e97f1b4a4030"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "0798280253ebab1fd9017b2ae017d6f99f4da4b55810a1dbb5da948e3593be0e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "b4967c557c5aedda4bef326f8e1dd7b9d8f35ee0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "4ac48570a969d7737492ffe0719c35461c072ce1182b6e4a7cd063673f512c0b"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "fe7ecc23eb3f5c0ffa052c90f4917b481e89b0fe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "041bf5c577ae48a95a9973791eeaba39dc5acd1da9366f1f21e2e2d6eb65ff8d"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "03965788c7c081aca5e709806af69013ebee162c"
libgfortran_version = "4.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "a414a41392b80461df9d1d1b0c2462997b829b02156b090f3ba6c1318bbbf6f9"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "3135bf588a05edd115ae767b3d770f2ae26eeaac"
libgfortran_version = "5.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "b7e829683ca938b67299e212928a75cf7e9a32aa75dd63ce358536329906dd92"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "ad4cc7559327723893a12844f00479c7d66fc420"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "06776c754b8323c6dcd359fff54bb74662bbd0b93d477cdf5234cec1aa709d4b"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "c16d0ad2604e4470b1b57eb8f55610b6988829c7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "e1754b99aec549b96ca4c5e7504b16ce03bf1923e32659a7135df9175cf2896c"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "d8b21f56433793787c4aafd2ae428115468bae9e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "10bf6419e35e7ac986db92c5ee7ffdd182add2aaba737ee0f5561b8c345e04a0"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "a6e282be5558f1981dc776967befd305a87ca61e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "2c4572092254533f182ecf9f94647deda1dd7b45d2ffd9a2a6752e1339ed7814"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "eb480f3f5fca28b09e63eb04ace41b8a39f5774b"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "4787c5b133d09b3822f6d82f7176c728adee3600274c0c147d7629e2f3ab2a3d"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "4c29a8f380c5e9d802546490adc45988368088d7"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "203ef42f213caaee8573123cff2dcf920e4129f698aeaf5809ad3bacba018936"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "b27b05832887ac0f0e1b94a3ff15f9ac019b8625"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "942265739dc1e9c8affe453558aeffc1bcf1133ec1880a870f5712b969665480"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "afff2c1563a4d6694bd41e544733a793915403af"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "9df3daa3c6b53b68f01c254757538b6e4786e7bead0668466af1f89bbf443277"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.1+1/qr_mumps.v3.0.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
