[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "564f15596be3ad6fa8a7cfc77ea0c55ab185f0ad"
libgfortran_version = "5.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "5255a12e93c341242fcca2774d55d2a598c38a3a73da4ec3e0b29109a0a1215e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "4b6cfbbc14695f72489ac5afb113f3536ad40688"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "8566a4bfb70db6268728ca3114ef8cc622eaffd317a07764bfe98d4e246d5b4a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "d180db3da53041323af1e303abc3be5e85aba5c8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "a5f8d81bd61ad375baea92a81e4421aae3b5675db4e258ad89d4e975eda6a52a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "65f8ed1ead30e39360fd14013007e32e3080392d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "e214c9e6aa1945fc2126b336bf5e797c06c529cd663109f41312d47aac25584e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "728f4244dd9ffdb4a1d15cc9925627ef02d129dd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "87cb182873e7e3828ae482d9eb45a4f2208afc66e0c4b7f2f6a696c43c03fb13"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "63df57965acb3776018103a2d6a7dce5125e4167"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "c294baa9d1c019b5ccf50b2ce09ac7ff415826b4ad409d95a9eb1eef6cca0428"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0630c6a3669f285a243180ab2d66c63a82ac73cf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "83c4099d2ab439f190d6776efdb4f1d26be563d920737d421b8db167069b5ebd"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "10c28152d84d7df68c4f4acdba5816a6538d8ee2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "c3746555735103be45be5a5a585cd20ffdd3e18cf0c464c1c2cd5a8c7a31ce5a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4b7c91773de92c9621ce3d18de0b595f96b12196"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "eacd0afa617a79c8226134ac334d9f21946c025af35a44a41adddd9f921c239a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f9f95a3f0e97f8823dd67326516cd91007cf0aa0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "175db2f1f15535b24e56b52170c99ad95501ab8a8eb19e512e51e92b0efe895f"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "438d098d963d3861d2005e873d1fab874190bd2d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "f85e8e8b2b1984a7a9437e1d5ca1b1058abd49873e30fccf280498e17668a7ac"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d96bc52f2c5dbb13a3f7374a95bc0a64237ce89"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "d687619fd86c2d32df53baa41486dcc81e43a3db84d2e714370ea96b69c86b71"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5011396cb0d7d61e53ee7975ad23c3dadacea594"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "aea1020f4c01ad7878082742c294d047fe1877dc76e12120f7e531f83910869a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "f0a4ef3bd1a62ced589af75e0e9f97f0151d6e60"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "5126397fd69978af93ae7fe91f37ffa08407ddcb4d129dd93f9c2bc0d1d502e9"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.i686-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "e291b1ea626dc1b76357fe694999b08756539835"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "b0e6bf35b621c9889cc531dc7cd4879d426b886da892660307badba2dcf7fd55"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.i686-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "5d2e3f7cc660f948f3e253d64404de1d1d7f0692"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "baad2f5f79f3c18708a3edea8212105ed0769aaaf27c7796eb7fa86449bf5da8"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.i686-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "4cd62cca78b6f089a97be0001813a1df72e41d2a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "570e9088a1734d0cf865e6e3c5bda08b7531058f9aa18f66d4b30b693bf9735f"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.i686-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "3b3522711e7f41a64be8ef6959b3e773a00d45c3"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "565c3c912742c59d0d3654b82b0fa7e4cbcbc639d03e4bac488bf0c81da9c8c9"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.i686-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "3cb3b9e77fe7c1a6e34b50c3c86f92d82d88e632"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "5c5923bdf8b3068b30fdc4c7fa3c2e3663c73dfd556a9d89649933c79480c78a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.i686-w64-mingw32-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "68ed7d3a181c3a9b224fc5ac726d6064b4ad186b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "2d6c30404f02b0e7a40b5063239ae7ac90a9e876aff0397a0019158896445d8e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "918717efcfb86e33ee28b5eee7cc1bf52d370b55"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "d71a5d89a3c32eca3bf2185a79a807fb0f773059c73ed16244d3a719d88c8eae"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "44b1ccb22215b385c1c054b87cdafe9e79c7cf02"
libgfortran_version = "4.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "64cd115c4bb7fc8b82ce52bf379bf6e663f72c140b694b4c4fa2f47c0e4f85b1"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "32d51587464a129a29dcc6a1c5468e10b151e8c6"
libgfortran_version = "5.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "68689fe1f452f961e044763f5b724a01dcb1ce5b62f47af62d0f9e6b0d4beeef"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "01e713544be20950e991a3de2428dbfc40cd488a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "315b4a45aae25a7e24f5d7b41f5ec35acc25049deb1b93b7474899fa868c8842"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "66af931638515cdbb604e4e982e777abf7b12198"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "a1c2c8e657936a388cf470a5ff4c8c3ffaa0c39081b9af3e0b7449b01abd212a"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "508d19d7565506400425f68596cbef1f4d1fec4a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "dc5d60752eb4361820fb51deadb41c6529710441607c7d7982d85ac0f824edfa"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "45158f8aac25748128f77d0cda8f07f5e2e542d6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "365ccf6957cf8b3e60a06aaace83b3e93f4a74b3b188bdabc7c947099a27ea6d"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "51dab98917882e71979c52fd096567ea4c93f85d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "a0e61653bafb8d208de8c33043b95f41affda7c988e59e5973760b9cc9392c5e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "cd9cb8971f796523b0a7303c5d645cb9e96a2bc6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "e9ee7e6996c22a8f445039866ef95e713316a5e9bc0c9151914ae3d5610c0a61"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "d23546bbe60a0846f2a7fd9de0c3d3ca1188b28e"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "8e15c6a654b52420a371a5bf10def239043bd257daf5f0ec0db5a795f6bad084"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "b92138526f548c728091a714ebbbacec1c0caf1a"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "97b002a6a155c80294a5631ad437dd5d2fee33392464c801d844c938871e05b3"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.5+0/qr_mumps.v3.0.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
