[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "222ad8d855d367edd139c023d96ecc3d0341742a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "8d2d92fc1f8099491856369f395af5b7f52cfb5ba59393bcb2cf35a86afcd407"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "f4ea53879e95c594930926971f2687889616538a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "21dafacc2126f7c2e7f5ff5a05e92cbfe45ae7ff323a12f0cb972b7e02215065"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "a789d0f69e114152dffdce62bb367514503684a9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "01eaeadfffb3d40a69b4c84e19eb351ea7703ae172e728bf772d3e517f7d894c"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "aarch64"
git-tree-sha1 = "9443135dad2754afb37edc621b5721d36bfa8f45"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "2eacdc4f0a8285825e4fa16f3b52d387ad2fcc6fb8fdc9f53b0b0127852887bf"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "248b537464505d0c2faa4825aa718dd8393258fa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "e226f864914753898d81552f68179d26268650f0fbbe905551be79251e6296d4"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a156a776f812863cef5e0670ea2246c95ea05d4a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "be469ac98e8e9f57a4ac419951f007c793e2f111a80506bbc1487c9db3b7b1f2"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ee2ea1db7f2dd9e4885d084057774ae916931982"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "a32ac7bc4ba817a7c5721a7064413475c6b7b8b25fac8db31692bc994fdd4fd0"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "637e0ed3785db1ae31393704a9788265bef7b7e5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "92698e977c773536889413755907fd0396286f0334e248547004d4c1a80b382d"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "d2de64cc21a87945277970d898a044f9e2e3efe1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "fef8506d56386c16f6f8528a1cd8db786b96858d9b0c14fdd49e2ecf09c64e9f"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.i686-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "6e506953b5bf1b06a46b47b1be2f51699caf50de"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "df6cc05b8c3e73dcd31129b9743bc0367636384c8b55db312220f8deeb3acfb6"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.i686-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "8fc542a2d44bdca1ab3102bc0a3ed94b8c630ea2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "89e4c708aff1779055c8510d1833452965e4e1a49ab367ec37dff9b242a1f94d"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.i686-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "20c5efb90bf3f7920b184965653afda69231dc70"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "6c247c607051d33ae253faeeddf4e1728c2def4ad1e82b82d287f32a2e989786"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.i686-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "b021adb96a039866b227aa7b72e7daeda1e5560b"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "11c14c00eb16f1930d2b3e439ce61837f38b56eb68863b9c56d6f2d3a018599c"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "i686"
git-tree-sha1 = "5fa11b6e31de317d781f4128336beb6c47bbe041"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "be4f36e50869ee76258ce81bcd20023a5e167e0ded9b0c15bffbc780633e3c78"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "7783f89d88b18c3cc950aa8ec16453237aedebd3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "399fc8c71ff0e9ea272f9bb05ac929eafd73db536026d36039c7ebd3cae3a055"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "powerpc64le"
git-tree-sha1 = "701c2b9d7bf576896600e15f92c6efff72bc6c77"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "2a125c79e7b2e1c82d0e394d4eff429ad14e4a40099a8a657c862e3e04f2913e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "5e163e1942448301df81d1a23175100c74122b80"
libgfortran_version = "4.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "6a3bc695f66e5532db1e93b29ad36957b40faab39f5b312090ee228560634fb0"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "6bbbb5091198b85913e3a69111915d00f7249ed9"
libgfortran_version = "5.0.0"
os = "macos"

    [[qr_mumps.download]]
    sha256 = "be413bad067a220737c9ed7542204ef11122c4fc38e36c232bb1367d33ebe772"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "39ee5437bbce4f34538c609bbb09b250107f7a4f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "c7b591dc4ac2c2632dfac5b2c4fb23b9cca100211c373e7627137468efde4d64"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "0db1c65be91512e4789cadff36ba22eafbaf1003"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "32f5ce706be4051e7698de2bfed305577a211a13cef22b1a338d841509ac1fd8"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "0ec12527e265c766b486c5d95aa3c807f8c94fe0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "8bfcfd9122cabe35da739c7b85836087c1da5ba2823d490ff4561a03245ef280"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "ec701b9752229013f5ff95fd6794e02729f83d3b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[qr_mumps.download]]
    sha256 = "535361092eca5b566a6e78ac754522c3b24ab28189cac5df5bd696620e1ad27e"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "c71649765e58a35a64fa443e6c598e639d4bc8b6"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "70f8d9317b8d747eb61440b9b719f9809e001fe73d2be665d0ff122c80005541"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "6534c943dfb59e54aa5cac82630741bc24ccde7e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[qr_mumps.download]]
    sha256 = "28c2437e75554124b1df34d7667f3333624510897e6abda34580f8e2c586e989"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "eb8b767806575cbcdddd11ec1e36c964dd24b101"
libgfortran_version = "4.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "26a4772794e530363bae8f5500c6d7e889981fd1adaf97877ef595bee35efc96"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[qr_mumps]]
arch = "x86_64"
git-tree-sha1 = "0e6981f6c2a459c0f0d0c1378ab7b13faa1982f1"
libgfortran_version = "5.0.0"
os = "windows"

    [[qr_mumps.download]]
    sha256 = "1ca0442a18eed852f8845f56791949123f60d589eaa92bd81a7c513552bb2153"
    url = "https://github.com/JuliaBinaryWrappers/qr_mumps_jll.jl/releases/download/qr_mumps-v3.0.2+4/qr_mumps.v3.0.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
